# this example doesn't care if aap 2.5 is running on openshift or not
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - group_vars/eda.yml
  vars:
    tower_host: "{{ tower.host }}"
    tower_user: "{{ tower.user }}"
    tower_pass: "{{ tower.pass }}"
  environment:
    CONTROLLER_HOST: "https://{{ tower_host }}/"
    CONTROLLER_USERNAME: "{{ tower_user }}"
    CONTROLLER_PASSWORD: "{{ tower_pass }}"
    CONTROLLER_VERIFY_SSL: false
  tasks:
  - name: Create EDA Projects
    ansible.eda.project:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      url: "{{ item.url }}"
      organization_name: "{{ item.org }}"
      state: present
    loop: "{{ eda_projects }}"

  - name: Create EDA Credentials
    ansible.eda.credential:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      inputs: "{{ item.inputs }}"
      credential_type_name: "{{ item.type }}"
      organization_name: Default
    loop: "{{ eda_creds }}"

  - name: Create EDA Decision Environments
    ansible.eda.decision_environment:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      image_url: "{{ item.url }}"
      credential: "{{ item.cred }}"
      organization_name: "{{ item.org }}"
      state: present
    loop: "{{ eda_de }}"

  - name: Create EDA Event Streams
    ansible.eda.event_stream:
      name: "{{ item.name }}"
      credential_name: "{{ item.cred }}"
      organization_name: "{{ item.org }}"
      forward_events: "{{ item.forward_events }}"
    loop: "{{ eda_streams }}"

  - name: Create rulebook activations with event_streams option
    ansible.eda.rulebook_activation:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      project_name: "{{ item.project }}"
      rulebook_name: "{{ item.rulebook }}"
      decision_environment_name: "{{ item.de }}"
      state: enabled
      organization_name: "{{ item.org }}"
      event_streams: "{{ item.event_streams }}"
      eda_credentials: "{{ item.eda_creds }}"
    loop: "{{ eda_rulebooks }}"
