---
- hosts: localhost
  connection: local
  vars:
    project: "{{ tower.project }}"
    destroy: no
  collections:
    - redhat.openshift
  tasks:
  - name: see if you really want to do this
    block:
    - name: "Destroy aap cluster k8s namespace"
      redhat.openshift.k8s:
        name: "{{ project }}"
        api_version: v1
        kind: Namespace
        state: absent
      when: destroy | bool
    
    rescue:
    - name: "do you really want to do this? be explicit"
        msg: |
          this will destroy the namespace {{ project }}. if you really want to do this, rerun the playbook setting the destroy parameter to true/yes.
          ansible-playbook -e 'destroy=yes' osp-destroy-aap.yml
