---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Pass event.payload to template
      condition: event.payload is defined
      action:
        run_job_template:
          name: 'Pause X minutes'
          organization: Default
          job_args:
            extra_vars:
              x: '1'
              msg: "payload: {{ event.payload.results._raw }}"
