---
- name: Listen for events on a webhook
  hosts: web
  ## Define our source for events
  sources:
     - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    ## Define the conditions we are looking for 
    - name: run if message has aws 
      condition: event.payload != null
    ## Define the action we should take should the condition be met  
      action:
        run_job_template:
          name: 'Pause X minutes'
          extra_vars: "{{ event.meta }}"
          organization: Default
                                
                                
